services:
    # db:
    #   image: postgres:latest
    #   environment:
    #     POSTGRES_USER: ${POSTGRES_USER}
    #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    #     POSTGRES_DB: ${POSTGRES_DB}
    #   volumes:
    #     - ./storage/Schema.sql:/docker-entrypoint-initdb.d/init.sql
    #   ports:
    #     - "5531:5432"
    redis:    
        image: redis:latest    

    webapi:
        image: rate-limited-svc
        # depends_on:      
        #      redis:
        #         condition: service_started
        ports:      
             - "3010:3010"
        # environment:      
        #     - REDIS_HOST=redis

