{
 "title": "Rate limit throttling",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Sliding Window Results",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"rate_limiter_metrics\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"request_logs\")\r\n  |> filter(fn: (r) => r[\"_value\"] == 201 and r.rateLimiter == \"sliding\")\r\n  |> aggregateWindow(every: 1m, fn: count, createEmpty: false)"
    },
    {
     "query": "from(bucket: \"rate_limiter_metrics\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"request_logs\")\r\n  |> filter(fn: (r) => r[\"_value\"] == 429 and r.rateLimiter == \"sliding\")\r\n  |> aggregateWindow(every: 1m, fn: count, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Token Window Results",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"rate_limiter_metrics\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"request_logs\")\r\n  |> filter(fn: (r) => r[\"_value\"] == 201 and r.rateLimiter == \"token\")\r\n  |> aggregateWindow(every: 1m, fn: count, createEmpty: false)\r\n"
    },
    {
     "query": "from(bucket: \"rate_limiter_metrics\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"request_logs\")\r\n  |> filter(fn: (r) => r[\"_value\"] == 429 and r.rateLimiter == \"token\")\r\n  |> aggregateWindow(every: 1m, fn: count, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Fixed Window Results",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"rate_limiter_metrics\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"request_logs\")\r\n  |> filter(fn: (r) => r[\"_value\"] == 201 and r.rateLimiter == \"fixed\")\r\n  |> aggregateWindow(every: 1m, fn: count, createEmpty: false)\r\n"
    },
    {
     "query": "from(bucket: \"rate_limiter_metrics\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"request_logs\")\r\n  |> filter(fn: (r) => r[\"_value\"] == 429 and r.rateLimiter == \"fixed\")\r\n  |> aggregateWindow(every: 1m, fn: count, createEmpty: false)"
    }
   ]
  }
 ]
}