POST http://localhost:3003/rides
content-type: application/json
userid: c1095838-c641-454d-a78c-0432ee8afaca

{
    "sourcelatitude": 47.1234,
    "sourcelongitude": -122.5678,
    "destinationlatitude": 46.4321,
    "destinationlongitude": -122.8765,
    "fare": 2378,
    "passengers": 2
}