services:
    db:
      image: postgres:latest
      environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
      volumes:
        - ./storage/Schema.sql:/docker-entrypoint-initdb.d/init.sql
      ports:
        - "5532:5432"
    redis:
        image: redis:latest    

    leet-main-svc:
        image: leet-main
        depends_on:
             db:
                condition: service_started
             kafka:
                condition: service_started
             redis:
                condition: service_started
        ports:      
             - "3004:3004"
        environment:
            - POSTGRES_HOST=db
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
        # environment:      
        #     - REDIS_HOST=redis
    kafka:
      image: apache/kafka:latest
      container_name: lcbroker
      environment:
        KAFKA_NODE_ID: 1
        KAFKA_PROCESS_ROLES: broker,controller
        KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://lcbroker:9092,EXTERNAL://kafka:9094
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
        KAFKA_CONTROLLER_QUORUM_VOTERS: 1@lcbroker:9093
        KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
        KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
#        KAFKA_CREATE_TOPICS: "codesubmissions:1:1"
    code-runner:
        image: code-runner
        depends_on:
             leet-main-svc:
                condition: service_started
             kafka:
                condition: service_started
        environment:
            MAX_CODE_RUNNERS: 10
    # dn-code-runner:
    #     image: code-runner-svc
    #     depends_on:
    #          leet-main-svc:
    #             condition: service_started
    #          kafka:
    #             condition: service_started
    #     environment:
    #         MAX_CODE_RUNNERS: 10

    # ridesvc:
    #     image: ride-svc
    #     depends_on:
    #         db:
    #             condition: service_started
    #         kafka:
    #             condition: service_started
    #     ports:
    #          - "3003:3003"
    #     environment:
    #         - POSTGRES_HOST=db
    #         - POSTGRES_USER=${POSTGRES_USER}
    #         - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    #         - POSTGRES_DB=${POSTGRES_DB}
    # matchbgsvc:
    #     image: match-bgsvc
    #     depends_on:      
    #         redis:
    #             condition: service_started
    #         db:
    #             condition: service_started
    #         kafka:
    #             condition: service_started
    #     environment:
    #         - POSTGRES_HOST=db
    #         - POSTGRES_USER=${POSTGRES_USER}
    #         - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    #         - POSTGRES_DB=${POSTGRES_DB}
